### ISSUE TITLE
Document that hacc-box-02 (+others) reboots every ~7am CET

### ISSUE THREAD

**Issue by eddieh-xlnx** [fpgasystems/hacc#4]
Would it be possible to document that `hacc-box-02` (plus other machines?) are rebooted every day at around 7am CET?

Ideally, the booking system should also prevent me from making a booking across this reboot window too, so it's clear that I will lose access.

**Comment by jmoya82** [comment]
Thanks for your feedback!

I have added the section "Pipelines" in "Operating the cluster" (https://github.com/fpgasystems/hacc/blob/main/docs/operating-the-cluster.md#operating-the-cluster).

As I mention there, the deployment servers are booked for the pipeline execution window, so it is not possible that you loose connection during that period (as you are not allowed to book them). With the build server is a little bit different, and you should plan your compilation jobs taking into account that every Monday the server will reboot.

**Comment by eddieh-xlnx** [comment]
@jmoya82 Thanks for making the update! I can see that I'm now not able to book anything immediately beyond 06:44 CET. The only nitpick I have left about the booking system is that I can see that an entry for weekly maintenance for the `hacc-build-01` box between "Mondays 06:45" - "Mondays 07:15", but I don't see a similar entry for the deployment servers -- the booking system isn't clear that I can only book continuously up to 06:44 as it just gives me a generic error message.

Not a big deal now I've figured it out though. Please feel free to close this ticket; thanks again!

**Comment by jmoya82** [comment]
You will see the bookings for the deployment machines under "Future Bookings." Thanks!
